const selectors = {
  usernameInput: '#ctl00_PlaceHolderMain_txtAgentUsername',
  passwordInput: '#ctl00_PlaceHolderMain_txtAgentPassword',
  loginButton: '#ctl00_PlaceHolderMain_imgbtnAgentLogin',
  createCustomerButton:
    '#ctl00_m_g_16743fea_f61e_40a6_88af_bb7e6a226f48_ctl00_btnCreateNewCust',
  salutationDropdown: '#ctl00_PlaceHolderMain_ddlSalutation',
  firstNameInput: '#ctl00_PlaceHolderMain_txtFirstName',
  lastNameInput: '#ctl00_PlaceHolderMain_txtLastName',
  martialStatusDropdown: '#ctl00_PlaceHolderMain_ddlMaritalStatus',
  dobInput: '#ctl00_PlaceHolderMain_txtDOB',
  nationalityDropdown: '#ctl00_PlaceHolderMain_ddlNationality',
  occupationDropdown: '#ctl00_PlaceHolderMain_ddlOccupation',
  genderFemaleRadio: '#ctl00_PlaceHolderMain_rdbGender_1',
  genderMaleRadio: '#ctl00_PlaceHolderMain_rdbGender_0',
  nextPage1Button: '#fragment-1 > a',
  addressLine1Input: '#ctl00_PlaceHolderMain_txtPermanentLocation_AddressLine1',
  mailingAddresslineInput1:
    '#ctl00_PlaceHolderMain_txtMailLocation_AddressLine1',
  addressLine2Input: '#ctl00_PlaceHolderMain_txtPermanentLocation_AddressLine2',
  mailingAddresslineInput2:
    '#ctl00_PlaceHolderMain_txtMailLocation_AddressLine2',
  addressLine3Input: '#ctl00_PlaceHolderMain_txtPermanentLocation_AddressLine3',
  mailingAddresslineInput3:
    '#ctl00_PlaceHolderMain_txtMailLocation_AddressLine3',
  pincodeInput: '#ctl00_PlaceHolderMain_txtPermPincode',
  mailingPincodeInput: '#ctl00_PlaceHolderMain_txtPincode',
  pincodeSearchButton: '#ctl00_PlaceHolderMain_btnPermPinSearch',
  mailingPincodeSearchButton: '#ctl00_PlaceHolderMain_btnMailPinSearch',
  mobileNumberInput:
    '#ctl00_PlaceHolderMain_txtPermanentLocation_ContactDetails_MobileNo',
  pincodeAreasDropdown: '#ctl00_PlaceHolderMain_ddlPermLocality',
  mailingPincodeAreasDropdown: '#ctl00_PlaceHolderMain_ddlLocality',
  mailingMobileNumberInput:
    '#ctl00_PlaceHolderMain_txtMailLocation_ContactDetails_MobileNo',
  nextPage2Button: '#fragment-2 > a.next-tab.mover',
  copyHomeAddressCheckbox:
    '#ctl00_PlaceHolderMain_chkPermanentLocationSameAsMailLocation',
  nextPage3Button: '#fragment-3 > a.next-tab.mover',
  nextPage4Button: '#fragment-4 > a.next-tab.mover',
  saveDetailsButton: '#ctl00_PlaceHolderMain_btnSave',
  createNewPolicyButton: '#ctl00_PlaceHolderMain_btnNewPolicy',
  corporateRadio: '#ctl00_PlaceHolderMain_rdbCustomerType_0',
  companyNameInput: '#ctl00_PlaceHolderMain_txtFirstName',
  vehicleTypeDropdown:
    '#ctl00_m_g_3c957951_3ef4_437d_988c_6cda31ac17aa_ctl00_ddlProduct',
  proceedButton:
    '#ctl00_m_g_3c957951_3ef4_437d_988c_6cda31ac17aa_ctl00_btnProceed',
  productTypeDropdown: '#ctl00_PlaceHolderMain_ddlProductType',
  relationshipCodeDropdown: '#ctl00_PlaceHolderMain_ddlRelation',
  vehicleRegistrationDate: '#ctl00_PlaceHolderMain_txtRegDate',
  rtoLocationInput: '#ctl00_PlaceHolderMain_txtSearchRegLocation',
  rtoLocationList: '#ui-id-1 > li > a',
  monthDropdown: '#ctl00_PlaceHolderMain_ddlMakeMonth',
  yearDropdown: '#ctl00_PlaceHolderMain_ddlMakeYear',
  manufacturerInput: '#ctl00_PlaceHolderMain_txtSearchMan',
  manufacturerList: '#ui-id-3',
  modelInput: '#ctl00_PlaceHolderMain_txtSearchModel',
  modelListHonda: '#ui-id-7',
  modelListOthers: '#ui-id-5',
  vehicleIdvInput: '#ctl00_PlaceHolderMain_txtIDV',
  higherIdvValue: '#ctl00_PlaceHolderMain_txtHigherIDV',
  lowerIdvValue: '#ctl00_PlaceHolderMain_txtLowerIDV',
  engineNumberInput: '#ctl00_PlaceHolderMain_txtEngineNumber',
  chassisNumberInput: '#ctl00_PlaceHolderMain_txtChasisNo',
  discountInput: '#ctl00_PlaceHolderMain_txtDetariff',
  tppdLimitDropdown: '#ctl00_PlaceHolderMain_ddlTPPDLimit',
  financedYesCheckBox: '#ctl00_PlaceHolderMain_chkIsVehicleFinanced',
  financierNameInput: '#ctl00_PlaceHolderMain_txtFIN2',
  financierList: '#ui-id-39',
  addOnCoverPlanDropdown: '#ctl00_PlaceHolderMain_ddlPlanNameLOV',
  existingPaCoverCheckbox: '#ctl00_PlaceHolderMain_chkHasExistingPA',
  compulsoryPaCoverCheckbox: '#ctl00_PlaceHolderMain_chkPAOwnerDriver',
  individualPersonalAccidentCheckbox: '#ctl00_PlaceHolderMain_chkIPA',
  continuePolicyIssuanceNotFoundInVahaan:
    '#ctl00_PlaceHolderMain_btnYesForVAHAN',
  chooseNoForWhatsappNotifications: '#btnWANO',
  gstPopupClose: '#close > a',
  calculatePremiumButton: '#ctl00_PlaceHolderMain_btnViewProposal',
  viewWorksheetButton: '#ctl00_PlaceHolderMain_btnViewWorksheet',
  havePreviousPolicyCheckbox: '#ctl00_PlaceHolderMain_chkPrevPolicyApplicable',
  previousInsurerDropdown: '#ctl00_PlaceHolderMain_ddlPSTPOL1',
  previousPolicyNumberInput: '#ctl00_PlaceHolderMain_txtPSTPOL2',
  previousInsurerAddressInput: '#ctl00_PlaceHolderMain_txtPSTPOL3',
  previousOdPolicyStartDateInput: '#ctl00_PlaceHolderMain_txtPSTPOL4',
  previousOdPolicyEndDateInput: '#ctl00_PlaceHolderMain_txtPSTPOL5',
  previousTpPolicyStartDateInput: '#ctl00_PlaceHolderMain_txtPSTPOL12',
  previousTpPolicyEndDateInput: '#ctl00_PlaceHolderMain_txtPSTPOL13',
  noOfClaimsInput: '#ctl00_PlaceHolderMain_txtPSTPOL6',
  previousPolicyTypeDropdown: '#ctl00_PlaceHolderMain_ddlPrevpolicyType',
  businessTypeDropdown: '#ctl00_PlaceHolderMain_ddltypeofbusiness',
  previousYearNCBDropdown: '#ctl00_PlaceHolderMain_ddlPrevYearNCB',
  addPreviousPolicyDetailsButton: '#ctl00_PlaceHolderMain_cmdAddPSTPOL',
  registrationNumberInput3: '#ctl00_PlaceHolderMain_txtPermanentRegNo3',
  registrationNumberInput4: '#ctl00_PlaceHolderMain_txtPermanentRegNo4',
  saveProposalButton: '#ctl00_PlaceHolderMain_btnCalculatePremium',
  validPucCheckbox: '#ctl00_PlaceHolderMain_chkValidPUCHolder',
  addOnInPreviousPolicyNoCheckbox: '#ctl00_PlaceHolderMain_chkAddonInPrevN',
  addOnInPreviousPolicyYesCheckbox: '#ctl00_PlaceHolderMain_chkAddonInPrevY',
  selectPreviousPolicyRecordCheckbox: '#chkDelPSTPOL1',
  pastPolicyTenureDropdown: '#ctl00_PlaceHolderMain_ddlPSTPOL12',
  serialNumberFinancerInput: '#ctl00_PlaceHolderMain_txtFIN1',
  financerAddressDropdown: '#ctl00_PlaceHolderMain_ddlFIN3',
  agreementTypeDropdown: '#ctl00_PlaceHolderMain_ddlFIN8',
  addFinancerDetailsButton: '#ctl00_PlaceHolderMain_cmdAddFIN',
  selectFinancerDetailsCheckbox: '#chkDelFIN1',
  totalPremiumValue: '#ctl00_PlaceHolderMain_lblNetPremium',
  gstOnTotalPremiumValue: '#ctl00_PlaceHolderMain_lblServiceTax',
  totalAmountPayableValue: '#ctl00_PlaceHolderMain_lblTotalPremium',
  ccInputValue: '#ctl00_PlaceHolderMain_txtCubicCapacity',
  proceedToPaymentButton: '#ctl00_PlaceHolderMain_btnProceed',
  paymentOptionDropdown: '#ctl00_PlaceHolderMain1_ddlPaymentOption',
  proceedToPaymentButton2: '#ctl00_PlaceHolderMain1_btn',
  aadhaarKycTypeRadio: '#ctl00_PlaceHolderMain_rdbKYC_2',
  aadhaarLastFourInput: '#ctl00_PlaceHolderMain_txtAADHAARNumber',
  kycDocumentButton: '#ctl00_PlaceHolderMain_rdbKYC_1',
  documentTypePanDropdown: '#ctl00_PlaceHolderMain_ddlKYCDOCType',
  supportingDocumentType: '#ctl00_PlaceHolderMain_ddlKYCDOCSuppType',
  kycErrorSpan: '#ctl00_PlaceHolderMain_lblKYCError',
  documentMainChooseFileButton: '#ctl00_PlaceHolderMain_fileKYCDOCUpload',
  mainDocumentUploadFileButton: '#ctl00_PlaceHolderMain_btnKYCDOCUpload',
  supportingDocumentChooseFileButton:
    '#ctl00_PlaceHolderMain_fileKYCDOCSuppUpload',
  supportingDocumentUploadFileButton:
    '#ctl00_PlaceHolderMain_btnKYCDOCSuppUpload',
  documentIdInput: '#ctl00_PlaceHolderMain_txtKYCRESPID',
  supportingDocumentId: '#ctl00_PlaceHolderMain_txtKYCRESPSuppID',
  kycTypeRadio: '#ctl00_PlaceHolderMain_rdbKYC_0',
  kycDocumentTypeDropdown: '#ctl00_PlaceHolderMain_ddlCKYCTypeOfID',
  kycDocumentIdInput: '#ctl00_PlaceHolderMain_txtCKYCIDNumber',
  kycIdNameInput: '#ctl00_PlaceHolderMain_txtCKYCNameAsID',
  kycIdDobInput: '#ctl00_PlaceHolderMain_txtCKYCDOB',
  kycVerifyButton: '#ctl00_PlaceHolderMain_btnCKYCFetch',
  payerTypeIntermediary: '#ctl00_PlaceHolderMain_rblPayerType_0',
  savePolicyButton: '#ctl00_PlaceHolderMain_btnSave',
  kycDocumentsRadio: '#ctl00_PlaceHolderMain_rdbKYC_1',
  documentTypeDropdown: '#ctl00_PlaceHolderMain_ddlKYCDOCType',
  corporateCkycDocumentIdType: '#ctl00_PlaceHolderMain_ddlCKYCTypeOfID',
  corporateDateOfIncorporationInput: '#ctl00_PlaceHolderMain_txtCKYCDOI'
};

export default selectors;
